### ISSUE TITLE
Error when a block is found

### ISSUE THREAD

**Issue by trampk** [EvrmoreOrg/evrmore-stratum-proxy#3]
![1](https://user-images.githubusercontent.com/10791352/203523035-123a5edf-9ebe-41b4-8e33-d796554dac63.PNG)

For several days everything worked well, the blocks were located and there were no problems. Yesterday I got this error

**Comment by kralverde** [comment]
https://github.com/EvrmoreOrg/evrmore-stratum-proxy/commit/561ea81e96923a304bcec68c76790356f1ac2e29
